from . import cf_mail_account
from . import cf_mail_message
from . import cf_mail_tag
from . import cf_mail_crm
from . import cf_contact
from . import cf_mail_compose
from . import cf_mail_sender_rule
from . import casafolino_mail_account
from . import casafolino_mail_message_staging
from . import casafolino_mail_blacklist
from . import crm_lead_ext
