from . import cf_contact
from . import casafolino_mail_account
from . import casafolino_mail_message_staging
from . import casafolino_mail_sender_policy
from . import crm_lead_ext
from . import casafolino_mail_tracking
from . import sla_partner
from . import orphan_partner
from . import lead_score
from . import snippet
from . import snippet_picker
from . import sender_decision
