{
    "name": "CasaFolino — Fancy Food NY 2026 Follow-up",
    "version": "18.0.1.0.0",
    "summary": "Sistema follow-up post-fiera Summer Fancy Food NY 2026: mail EN/IT, catalogo tokenizzato, tracking engagement.",
    "author": "CasaFolino",
    "license": "LGPL-3",
    "category": "Marketing",
    "depends": [
        "base",
        "mail",
        "contacts",
        "crm",
        "base_automation",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/fancyfood_tags.xml",
        "data/mail_template_en.xml",
        "data/mail_template_it.xml",
        "data/server_action.xml",
        "data/base_automation.xml",
        "views/fancyfood_event_views.xml",
        "views/res_partner_views.xml",
    ],
    "installable": True,
    "application": False,
}
