# -*- coding: utf-8 -*-
{
    "name": "Scrivania CasaFolino",
    "version": "18.0.2.1.0",
    "category": "Productivity",
    "summary": "Scrivania CasaFolino — cockpit aziendale con CRM, Produzione, HACCP e Tesoreria",
    "author": "CasaFolino Srls",
    "depends": [
        "base", "web",
        "casafolino_commercial",
        "casafolino_crm_export",
        "casafolino_haccp",
        "casafolino_initiative",
        "casafolino_kpi",
        "casafolino_labels",
        "casafolino_mail",
        "casafolino_operations",
        "casafolino_product",
        "casafolino_project",
        "casafolino_supplier_qual",
        "casafolino_workspace",
    ],
    "post_init_hook": "_post_init_hook",
    "data": [
        "security/ir.model.access.csv",
        "views/home_actions.xml",
        "views/menu_workspace.xml",
        "data/menu_remap.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "casafolino_home/static/src/workspace/workspace.scss",
            "casafolino_home/static/src/workspace/workspace.xml",
            "casafolino_home/static/src/workspace/workspace.js",
        ],
    },
    "installable": True,
    "application": True,
    "license": "LGPL-3",
    "icon": "casafolino_home/static/description/icon.png",
}
