{
    'name': 'CasaFolino Initiative Dashboard',
    'version': '18.0.4.0.0',
    'summary': 'Lavagna cockpit OWL — scrivania virtuale azionabile con CRUD task, todo, campioni, lead',
    'category': 'CasaFolino',
    'author': 'CasaFolino',
    'depends': [
        'casafolino_initiative',
        'project',
        'mail',
        'crm',
        'calendar',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/cf_initiative_tag_source_data.xml',
        'data/dashboard_kpi_data.xml',
        'data/lavagna_template_data.xml',
        'data/cf_sample_request_sequence.xml',
        'views/cf_initiative_views.xml',
        'views/cf_sample_request_views.xml',
        'views/dashboard_kpi_views.xml',
        'views/lavagna_template_views.xml',
        'wizard/cf_initiative_wizard_views.xml',
        'views/menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            # Lavagne Attive open-on-click patch
            'casafolino_initiative_dashboard/static/src/js/lavagne_attive_open.js',
            # Wizard widgets (F1.2)
            'casafolino_initiative_dashboard/static/src/js/lavagna_family_cards.js',
            'casafolino_initiative_dashboard/static/src/xml/lavagna_family_cards.xml',
            'casafolino_initiative_dashboard/static/src/js/lavagna_scenario_cards.js',
            'casafolino_initiative_dashboard/static/src/xml/lavagna_scenario_cards.xml',
            'casafolino_initiative_dashboard/static/src/scss/wizard.scss',
            # Lavagna OWL cockpit (F2)
            'casafolino_initiative_dashboard/static/src/scss/lavagna.scss',
            'casafolino_initiative_dashboard/static/src/js/lavagna/lavagna_main.js',
            'casafolino_initiative_dashboard/static/src/js/lavagna/lavagna_header.js',
            'casafolino_initiative_dashboard/static/src/js/lavagna/lavagna_today_bar.js',
            'casafolino_initiative_dashboard/static/src/js/lavagna/lavagna_kpi_rail.js',
            'casafolino_initiative_dashboard/static/src/js/lavagna/lavagna_kanban.js',
            'casafolino_initiative_dashboard/static/src/js/lavagna/lavagna_task_card.js',
            'casafolino_initiative_dashboard/static/src/js/lavagna/lavagna_panel_mail.js',
            'casafolino_initiative_dashboard/static/src/js/lavagna/lavagna_panel_todo.js',
            'casafolino_initiative_dashboard/static/src/js/lavagna/lavagna_panel_activity.js',
            'casafolino_initiative_dashboard/static/src/js/lavagna/lavagna_panel_calendar.js',
            'casafolino_initiative_dashboard/static/src/js/lavagna/lavagna_drawer_task.js',
            'casafolino_initiative_dashboard/static/src/js/lavagna/lavagna_timeline.js',
            'casafolino_initiative_dashboard/static/src/xml/lavagna/lavagna_main.xml',
            'casafolino_initiative_dashboard/static/src/xml/lavagna/lavagna_header.xml',
            'casafolino_initiative_dashboard/static/src/xml/lavagna/lavagna_today_bar.xml',
            'casafolino_initiative_dashboard/static/src/xml/lavagna/lavagna_kpi_rail.xml',
            'casafolino_initiative_dashboard/static/src/xml/lavagna/lavagna_kanban.xml',
            'casafolino_initiative_dashboard/static/src/xml/lavagna/lavagna_task_card.xml',
            'casafolino_initiative_dashboard/static/src/xml/lavagna/lavagna_panel_mail.xml',
            'casafolino_initiative_dashboard/static/src/xml/lavagna/lavagna_panel_todo.xml',
            'casafolino_initiative_dashboard/static/src/xml/lavagna/lavagna_panel_activity.xml',
            'casafolino_initiative_dashboard/static/src/xml/lavagna/lavagna_panel_calendar.xml',
            'casafolino_initiative_dashboard/static/src/xml/lavagna/lavagna_drawer_task.xml',
            'casafolino_initiative_dashboard/static/src/xml/lavagna/lavagna_timeline.xml',
        ],
    },
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
