{
    'name': 'CasaFolino Initiative Dashboard',
    'version': '18.0.1.2.0',
    'summary': 'Lavagna cockpit + wizard setup con scenari multipli per iniziative CasaFolino',
    'category': 'CasaFolino',
    'author': 'CasaFolino',
    'depends': [
        'casafolino_initiative',
        'project',
        'mail',
        'crm',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/cf_initiative_tag_source_data.xml',
        'data/dashboard_kpi_data.xml',
        'data/lavagna_template_data.xml',
        'views/cf_initiative_views.xml',
        'views/dashboard_kpi_views.xml',
        'views/lavagna_template_views.xml',
        'wizard/cf_initiative_wizard_views.xml',
        'views/menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'casafolino_initiative_dashboard/static/src/js/dashboard_placeholder.js',
            'casafolino_initiative_dashboard/static/src/xml/dashboard_placeholder.xml',
            'casafolino_initiative_dashboard/static/src/js/lavagna_family_cards.js',
            'casafolino_initiative_dashboard/static/src/xml/lavagna_family_cards.xml',
            'casafolino_initiative_dashboard/static/src/js/lavagna_scenario_cards.js',
            'casafolino_initiative_dashboard/static/src/xml/lavagna_scenario_cards.xml',
            'casafolino_initiative_dashboard/static/src/scss/wizard.scss',
        ],
    },
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
