from . import crm_lead
from . import crm_lead_dashboard
from . import crm_tag
from . import res_partner
from . import project_project
from . import sale_order
from . import cf_crm_stage
from . import cf_mail_activity
from . import card_scanner
from . import cf_export_sample
from . import cf_export_fair
from . import cf_export_sequence
from . import res_config_settings
