{
    'name': 'CasaFolino Mail CRM',
    'version': '18.0.18.0.0',
    'summary': 'Pipeline fetch RAW → classificazione → MESSAGE + Cartelle + Mass Actions + Multi-utente per CasaFolino',
    'category': 'CasaFolino',
    'author': 'CasaFolino',
    'depends': ['base', 'mail', 'web', 'utm', 'crm'],
    'data': [
        'security/ir.model.access.csv',
        'security/ir_rules.xml',
        'views/casafolino_mail_hub_views.xml',
        'views/casafolino_mail_wizard_views.xml',
        'views/sla_partner_views.xml',
        'views/orphan_partner_views.xml',
        'views/lead_score_views.xml',
        'views/snippet_views.xml',
        'views/snippet_picker_views.xml',
        'views/sender_decision_views.xml',
        'views/casafolino_mail_raw_views.xml',
        'views/create_lead_wizard_views.xml',
        'views/casafolino_mail_folder_views.xml',
        'views/res_partner_mail_tracking_views.xml',
        'views/posizionatore_views.xml',
        'data/mail_v3_client_action.xml',
        'views/menus.xml',
        'data/snippet_seed.xml',
        'data/cf_mail_cron.xml',
        'data/cf_mail_config.xml',
        'data/cf_utm_sources.xml',
        'data/casafolino_mail_server_actions.xml',
        'data/casafolino_mail_hub_cron.xml',
        'data/cleanup_legacy_menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            # Brief #6.5 Inbox Selector
            'casafolino_mail/static/src/inbox_selector/inbox_selector.js',
            'casafolino_mail/static/src/inbox_selector/inbox_selector.xml',
            'casafolino_mail/static/src/inbox_selector/inbox_selector.scss',
            'casafolino_mail/static/src/inbox_selector/posizionatore_list_controller.js',
            'casafolino_mail/static/src/inbox_selector/posizionatore_list_controller.xml',
            # Brief #6.2 Posizionatore
            'casafolino_mail/static/src/posizionatore/posizionatore.scss',
            # Brief #6.4 Compose AI Panel
            'casafolino_mail/static/src/compose_ai_panel/compose_ai_panel.js',
            'casafolino_mail/static/src/compose_ai_panel/compose_ai_panel.xml',
            'casafolino_mail/static/src/compose_ai_panel/compose_ai_panel.scss',
            # V11 existing
            'casafolino_mail/static/src/js/snippet_clipboard.js',
            'casafolino_mail/static/src/xml/snippet_clipboard.xml',
            # [DEPRECATED Brief #6.0] triage_shortcuts.js removed
            # V3 SCSS
            'casafolino_mail/static/src/scss/mail_v3.scss',
            # V3 OWL components — JS
            'casafolino_mail/static/src/js/mail_v3/mail_v3_client.js',
            'casafolino_mail/static/src/js/mail_v3/mail_v3_sidebar_left.js',
            'casafolino_mail/static/src/js/mail_v3/mail_v3_thread_list.js',
            'casafolino_mail/static/src/js/mail_v3/mail_v3_reading_pane.js',
            'casafolino_mail/static/src/js/mail_v3/mail_v3_compose.js',
            'casafolino_mail/static/src/js/mail_v3/compose_wizard_dialog.js',
            'casafolino_mail/static/src/js/mail_v3/mail_v3_sidebar_360.js',
            'casafolino_mail/static/src/js/mail_v3/mail_v3_insight_360_tabbar.js',
            'casafolino_mail/static/src/js/mail_v3/mail_v3_reply_assistant.js',
            'casafolino_mail/static/src/js/mail_v3/mail_v3_analytics.js',
            'casafolino_mail/static/src/js/mail_v3/mail_v3_sender_decision_popup.js',
            'casafolino_mail/static/src/js/mail_v3/mail_v3_dismissed_senders.js',
            'casafolino_mail/static/src/js/mail_v3/mail_v3_folder_sidebar.js',
            'casafolino_mail/static/src/js/mail_v3/mail_v3_notifications.js',
            'casafolino_mail/static/src/js/mail_v3/mail_v3_sync_badge.js',
            # V3 OWL components — XML templates
            'casafolino_mail/static/src/xml/mail_v3/mail_v3_client.xml',
            'casafolino_mail/static/src/xml/mail_v3/mail_v3_sidebar_left.xml',
            'casafolino_mail/static/src/xml/mail_v3/mail_v3_thread_list.xml',
            'casafolino_mail/static/src/xml/mail_v3/mail_v3_reading_pane.xml',
            'casafolino_mail/static/src/xml/mail_v3/mail_v3_compose.xml',
            'casafolino_mail/static/src/xml/mail_v3/compose_wizard_dialog.xml',
            'casafolino_mail/static/src/xml/mail_v3/mail_v3_sidebar_360.xml',
            'casafolino_mail/static/src/xml/mail_v3/mail_v3_insight_360_tabbar.xml',
            'casafolino_mail/static/src/xml/mail_v3/mail_v3_reply_assistant.xml',
            'casafolino_mail/static/src/xml/mail_v3/mail_v3_analytics.xml',
            'casafolino_mail/static/src/xml/mail_v3/mail_v3_sender_decision_popup.xml',
            'casafolino_mail/static/src/xml/mail_v3/mail_v3_dismissed_senders.xml',
            'casafolino_mail/static/src/xml/mail_v3/mail_v3_folder_sidebar.xml',
            'casafolino_mail/static/src/xml/mail_v3/mail_v3_sync_badge.xml',
        ],
    },
    'post_init_hook': '_post_init_hook',
    'installable': True,
    'application': True,
    'license': 'OPL-1',
}
