{
    'name': 'CasaFolino Mail',
    'version': '5.0',
    'summary': 'Client email Gmail-style per CasaFolino',
    'category': 'CasaFolino',
    'author': 'CasaFolino',
    'depends': ['base', 'mail', 'web', 'utm', 'crm', 'casafolino_crm_export'],
    'data': [
        'security/ir.model.access.csv',
        'security/ir_rules.xml',
        'views/cf_mail_views.xml',
        'views/cf_mail_partner_views.xml',
        'views/cf_mail_sender_rule_views.xml',
        'views/casafolino_mail_hub_views.xml',
        'views/casafolino_mail_wizard_views.xml',
        'views/cf_mail_template_views.xml',
        'views/menus.xml',
        'data/cf_mail_cron.xml',
        'data/cf_mail_config.xml',
        'data/cf_utm_sources.xml',
        'data/casafolino_mail_server_actions.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'casafolino_mail/static/src/css/cf_mail_client.css',
            'casafolino_mail/static/src/css/cf_lead_mail_widget.css',
            'casafolino_mail/static/src/xml/cf_mail_client.xml',
            'casafolino_mail/static/src/xml/cf_lead_mail_widget.xml',
            'casafolino_mail/static/src/js/cf_mail_client.js',
            'casafolino_mail/static/src/js/cf_lead_mail_widget.js',
        ],
    },
    'post_init_hook': '_post_init_hook',
    'installable': True,
    'application': True,
    'license': 'OPL-1',
}
