{
    'name': 'CasaFolino Mail CRM',
    'version': '7.1',
    'summary': 'Ponte selettivo Gmail → CRM per CasaFolino',
    'category': 'CasaFolino',
    'author': 'CasaFolino',
    'depends': ['base', 'mail', 'web', 'utm', 'crm', 'casafolino_crm_export'],
    'data': [
        'security/ir.model.access.csv',
        'security/ir_rules.xml',
        'views/casafolino_mail_hub_views.xml',
        'views/casafolino_mail_policy_views.xml',
        'views/casafolino_mail_wizard_views.xml',
        'views/menus.xml',
        'data/cf_mail_cron.xml',
        'data/cf_mail_config.xml',
        'data/cf_utm_sources.xml',
        'data/casafolino_mail_server_actions.xml',
        'data/casafolino_mail_hub_cron.xml',
    ],
    'assets': {},
    'post_init_hook': '_post_init_hook',
    'installable': True,
    'application': True,
    'license': 'OPL-1',
}
