{
    'name': 'CasaFolino Commercial',
    'version': '18.0.2.4.6',
    'post_init_hook': '_post_init_bank_resilience',
    'category': 'CasaFolino',
    'summary': 'GDO, Private Label, Tesoreria e Blocchi Documento',
    'author': 'CasaFolino Srls',
    'depends': ['base', 'mail', 'sale_management', 'product', 'account', 'purchase'],
    'data': [
        'security/ir.model.access.csv',
        'data/account_tax_data.xml',
        'data/cf_fatturapa_xml_fix_actions.xml',
        'wizards/sale_discount_wizard.xml',
        'wizards/cf_bank_resilience_runner.xml',
        'data/cf_treasury_cron.xml',
        'views/cf_doc_footer_views.xml',
        'views/cf_gdo_views.xml',
        'views/cf_pl_views.xml',
        'views/cf_treasury_views.xml',
        'views/cf_treasury_liquidity_views.xml',
        'views/cf_treasury_receivables_views.xml',
        'views/cf_treasury_payables_views.xml',
        'views/cf_treasury_cashflow_views.xml',
        'views/cf_treasury_period_views.xml',
        'views/cf_sale_discount_views.xml',
        'views/cf_vendor_bill_decimal_views.xml',
        'views/menus.xml',
        'report/cf_doc_footer_report.xml',
        'report/sale_order_internal_report.xml',
    ],
    'assets': {
        'web.assets_backend': [
            ('prepend', 'https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js'),
            'casafolino_commercial/static/src/xml/cf_treasury_dashboard.xml',
            'casafolino_commercial/static/src/js/cf_treasury_dashboard.js',
            'casafolino_commercial/static/src/xml/cf_treasury_forecast.xml',
            'casafolino_commercial/static/src/js/cf_treasury_forecast.js',
            'casafolino_commercial/static/src/xml/cf_treasury_clients.xml',
            'casafolino_commercial/static/src/js/cf_treasury_clients.js',
            'casafolino_commercial/static/src/xml/cf_treasury_categories.xml',
            'casafolino_commercial/static/src/js/cf_treasury_categories.js',
            'casafolino_commercial/static/src/xml/cf_treasury_turnover.xml',
            'casafolino_commercial/static/src/js/cf_treasury_turnover.js',
        ],
    },
    'installable': True,
    'license': 'LGPL-3',
}
