{
    'name': 'CasaFolino Commercial',
    'version': '18.0.2.0.0',
    'category': 'CasaFolino',
    'summary': 'GDO, Private Label e Tesoreria completa',
    'author': 'CasaFolino Srls',
    'depends': ['base', 'mail', 'sale_management', 'product', 'account', 'purchase'],
    'data': [
        'security/ir.model.access.csv',
        'data/cf_treasury_cron.xml',
        'views/cf_gdo_views.xml',
        'views/cf_pl_views.xml',
        'views/cf_treasury_views.xml',
        'views/cf_treasury_liquidity_views.xml',
        'views/cf_treasury_receivables_views.xml',
        'views/cf_treasury_payables_views.xml',
        'views/cf_treasury_cashflow_views.xml',
        'views/menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            ('prepend', 'https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js'),
            'casafolino_commercial/static/src/xml/cf_treasury_dashboard.xml',
            'casafolino_commercial/static/src/js/cf_treasury_dashboard.js',
            'casafolino_commercial/static/src/xml/cf_treasury_forecast.xml',
            'casafolino_commercial/static/src/js/cf_treasury_forecast.js',
            'casafolino_commercial/static/src/xml/cf_treasury_clients.xml',
            'casafolino_commercial/static/src/js/cf_treasury_clients.js',
            'casafolino_commercial/static/src/xml/cf_treasury_categories.xml',
            'casafolino_commercial/static/src/js/cf_treasury_categories.js',
        ],
    },
    'installable': True,
    'license': 'LGPL-3',
}
