# -*- coding: utf-8 -*-
{
    "name": "CasaFolino Workspace",
    "version": "18.0.0.8.0",
    "post_init_hook": "_post_init_hook",
    "category": "Productivity",
    "summary": "Scrivania operativa CasaFolino",
    "author": "CasaFolino Srls",
    "depends": ["base", "web", "mail", "calendar", "crm", "project", "account", "stock", "casafolino_mail"],
    "data": [
        "security/ir.model.access.csv",
        "data/workspace_projects_seed.xml",
        "views/menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "casafolino_workspace/static/src/css/cf_workspace_client.css",
            "casafolino_workspace/static/src/xml/cf_workspace_client.xml",
            "casafolino_workspace/static/src/js/components/workspace_hero.js",
            "casafolino_workspace/static/src/js/components/workspace_kpis.js",
            "casafolino_workspace/static/src/js/components/workspace_macro.js",
            "casafolino_workspace/static/src/js/components/workspace_work.js",
            "casafolino_workspace/static/src/js/components/workspace_detail.js",
            "casafolino_workspace/static/src/js/components/workspace_feed.js",
            "casafolino_workspace/static/src/js/components/workspace_quick_actions.js",
            "casafolino_workspace/static/src/css/workspace_lead.css",
            "casafolino_workspace/static/src/css/workspace_proj.css",
            "casafolino_workspace/static/src/js/lead/workspace_lead.js",
            "casafolino_workspace/static/src/xml/workspace_lead.xml",
            "casafolino_workspace/static/src/js/proj/workspace_proj.js",
            "casafolino_workspace/static/src/xml/workspace_proj.xml",
            "casafolino_workspace/static/src/css/workspace_mail.css",
            "casafolino_workspace/static/src/js/mail/workspace_mail.js",
            "casafolino_workspace/static/src/xml/workspace_mail.xml",
            "casafolino_workspace/static/src/css/workspace_cal.css",
            "casafolino_workspace/static/src/js/cal/workspace_cal.js",
            "casafolino_workspace/static/src/xml/workspace_cal.xml",
            "casafolino_workspace/static/src/css/workspace_qa.css",
            "casafolino_workspace/static/src/js/qa/workspace_qa.js",
            "casafolino_workspace/static/src/xml/workspace_qa.xml",
            "casafolino_workspace/static/src/css/workspace_cash.css",
            "casafolino_workspace/static/src/js/cash/workspace_cash.js",
            "casafolino_workspace/static/src/xml/workspace_cash.xml",
            "casafolino_workspace/static/src/css/workspace_dec.css",
            "casafolino_workspace/static/src/js/dec/workspace_dec.js",
            "casafolino_workspace/static/src/xml/workspace_dec.xml",
            "casafolino_workspace/static/src/css/workspace_inv.css",
            "casafolino_workspace/static/src/js/inv/workspace_inv.js",
            "casafolino_workspace/static/src/xml/workspace_inv.xml",
            "casafolino_workspace/static/src/js/cf_workspace_client.js",
        ],
    },
    "installable": True,
    "application": True,
    "license": "LGPL-3",
    "icon": "casafolino_workspace/static/description/icon.png",
}
