from . import cf_gdo
from . import cf_private_label
from . import cf_treasury
from . import cf_treasury_cashflow
from . import cf_treasury_aml_ext
from . import cf_treasury_analytics
from . import sale_order_ext
from . import cf_doc_footer
from . import account_move_ext
from . import casafolino_fiera
