{
    'name': 'CasaFolino Export CRM',
    'version': '18.0.9.0.0',
    'category': 'Sales/CRM',
    'summary': 'CRM Export B2B operatore-centrico con scoring, rotting, campionature, fiere e card scanner AI',
    'author': 'CasaFolino S.R.L.',
    'depends': ['crm', 'sale', 'mail', 'contacts', 'documents', 'project'],
    'data': [
        'security/ir.model.access.csv',
        'data/cf_sample_stages.xml',
        'data/cf_sequence_data.xml',
        'data/cf_export_cron.xml',
        'data/cf_crm_stages_data.xml',
        'data/cf_crm_tags_market_channel.xml',
        'data/crm_tag_data.xml',
        'data/crm_tag_category_data.xml',
        'data/res_partner_category_data.xml',
        'data/utm_source_data.xml',
        'data/ir_config_parameter_data.xml',
        'data/mail_template_sial_montreal_en.xml',
        'data/mail_template_sial_montreal_fr.xml',
        'views/crm_lead_views.xml',
        'views/crm_lead_list_enriched_view.xml',
        'views/res_partner_views.xml',
        'views/project_project_views.xml',
        'views/cf_sample_views.xml',
        'views/cf_fair_views.xml',
        'views/res_config_settings_views.xml',
        'views/crm_lead_wizard_action.xml',
        'views/menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'casafolino_crm_export/static/src/css/cf_crm.css',
            'casafolino_crm_export/static/src/css/kanban_enriched.css',
            'casafolino_crm_export/static/src/css/list_view_enriched.css',
            'casafolino_crm_export/static/src/list_widgets/cf_card_title.js',
            'casafolino_crm_export/static/src/list_widgets/cf_owner_avatar_inline.js',
            'casafolino_crm_export/static/src/list_widgets/cf_stage_progress_inline.js',
            'casafolino_crm_export/static/src/list_widgets/cf_signals_badges.js',
            'casafolino_crm_export/static/src/list_widgets/cf_crm_lead_list_view.js',
            'casafolino_crm_export/static/src/list_widgets/cf_widgets.xml',
            'casafolino_crm_export/static/src/list_widgets/cf_crm_lead_list_view.xml',
            'casafolino_crm_export/static/src/components/card_scanner_widget.js',
            'casafolino_crm_export/static/src/components/card_scanner_widget.xml',
            'casafolino_crm_export/static/src/components/card_scanner_widget.scss',
            'casafolino_crm_export/static/src/js/cf_wizard_new_dialog.js',
            'casafolino_crm_export/static/src/xml/cf_wizard_new.xml',
            'casafolino_crm_export/static/src/css/wizard_new.css',
        ],
    },
    'post_init_hook': '_post_init_hook',
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
